# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-26 12:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Job ID')),
                ('remote_id', models.CharField(max_length=50, verbose_name='Remote Job ID')),
                ('status', models.CharField(choices=[(b'IN_PROGRESS', b'in progress'), (b'FAILED', b'failed'), (b'NOT_STARTED', b'not started'), (b'NOT_SUBMITTED', b'not submitted'), (b'COMPLETED', b'completed')], default=b'not submitted', max_length=20, verbose_name='Job Status')),
                ('date_time', models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0), verbose_name='DateTime')),
                ('variable', models.CharField(choices=[(b'u-wind', b'Eastward wind speed'), (b'v-wind', b'Northward wind speed'), (b'tas', b'Mean air temperature')], default=b'Mean air temperature', max_length=20, verbose_name='Variable')),
                ('input_file_path', models.CharField(blank=True, choices=[(b'data2.txt', b'eg_files/data2.txt'), (b'data3.txt', b'eg_files/data3.txt'), (b'data1.txt', b'eg_files/data1.txt')], max_length=200, null=True)),
                ('output_file_path', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
