# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('remote_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[(b'IN_PROGRESS', b'in progress'), (b'FAILED', b'failed'), (b'NOT_STARTED', b'not started'), (b'NOT_SUBMITTED', b'not submitted'), (b'COMPLETED', b'completed')], default=b'not submitted', max_length=20)),
                ('input_file_path', models.CharField(max_length=200)),
                ('output_file_path', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(max_length=30)),
                ('input_value', models.CharField(max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcapp.Job')),
            ],
        ),
    ]
