# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcapp', '0002_auto_20170530_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[(b'NOT_STARTED', b'not started'), (b'FAILED', b'failed'), (b'COMPLETED', b'completed'), (b'NOT_SUBMITTED', b'not submitted'), (b'IN_PROGRESS', b'in progress')], default=b'not submitted', max_length=20, verbose_name='Job Status'),
        ),
    ]
